[package]
name = "raytrace_rs"
version = "0.1.0"
authors = ["RystaC <mirage.s.cpp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
